---
title: "NLP_InitialAnalysis"
author: "DGK"
date: "2024-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Initialize Data

```{r}
library(readr)

fairuseindex <- read_csv("/Users/dgkamper/DGK_Lab/ReasoningLab/Fair Use Legal Corpus/Edited_Fair_Use_Index_Data.csv")
```

------------------------------------------------------------------------

### Frequencies

------------------------------------------------------------------------

#### Medium

```{r}
library (ggplot2)

# Medium Types Barplot
## We are plotting what is the frequencies of different mediums?

ggplot(fairuseindex, aes(x = Medium)) +
  geom_bar() +
  labs(title = "Frequency of Different Mediums", x = "Medium", y = "Frequency") +
  theme_minimal()+
  theme(
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  ) 
```

#### Jurisdiction

```{r}
library (ggplot2)

# Jurisdiction Types Barplot
## We are plotting what is the frequencies of different jurisdictions

ggplot(fairuseindex, aes(x = Jurisdiction)) +
  geom_bar() +
  labs(title = "Frequency of Different Jurisdictions", x = "Jurisdiction", y = "Frequency") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10, face = "plain"),
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  )
```

Notably, the Ninth Circuit is California, Oregon and Washington. The Second Circuit is New York and Connecticut.

#### Overall Fair Use Outcomes

```{r}
library(ggplot2)

# General counts for fair use outcomes
general_counts <- fairuseindex %>% 
  group_by(Outcome) %>% 
  summarize(Count = n())

print("General Fair Use Outcome Counts")
print(general_counts)

# General plot of Fair Use Outcome
ggplot(fairuseindex, aes(x = Outcome)) +
  geom_bar(fill = c("blue", "red")) +
  labs(title = "General Fair Use Outcome", x = "Outcome", y = "Frequency") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 10, face = "plain"),
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  )
```

#### Fair Use Outcome

```{r}
library(ggplot2)

# Medium by Fair Use Outcome
ggplot(fairuseindex, aes(x = Medium, fill = Outcome)) +
  geom_bar(position = "dodge") +
  scale_fill_manual(values = c("Fair use found" = "blue", "Fair use not found" = "red")) +
  labs(title = "Medium by Fair Use Outcome", x = "Medium", y = "Frequency", fill = "Outcome") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10, face = "plain"),
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  )
```

#### Specific Sectors

```{r}
library(ggplot2)

# Filter the dataset to include only rows with "Internet/Digitization" == 1
internet_data <- fairuseindex[fairuseindex$`Internet/Digitization` == 1, ]

# Bar plot of Fair Use Outcome for Internet/Digitization
ggplot(internet_data, aes(x = Outcome)) +
  geom_bar(fill = c("blue", "red")) +
  labs(title = "Fair Use Outcome for Internet/Digitization", x = "Outcome", y = "Count") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 10, face = "plain"),
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  )
```

```{r}
library(dplyr)

# Combine the columns "Films/Audiovisual" and "Film/Audiovisual" into one
fairuseindex <- fairuseindex %>%
  mutate(`Film/Audiovisual` = ifelse(is.na(`Film/Audiovisual`), 0, `Film/Audiovisual`) + 
                             ifelse(is.na(`Films/Audiovisual`), 0, `Films/Audiovisual`)) %>%
  mutate(`Film/Audiovisual` = ifelse(`Film/Audiovisual` > 1, 1, `Film/Audiovisual`)) %>%
  select(-`Films/Audiovisual`)

# Collapse the columns related to News Reporting into one
fairuseindex <- fairuseindex %>%
  mutate(`News Reporting` = ifelse(is.na(`News Reporting`), 0, `News Reporting`) + 
                            ifelse(is.na(`News reporting`), 0, `News reporting`)) %>%
  mutate(`News Reporting` = ifelse(`News Reporting` > 1, 1, `News Reporting`)) %>%
  select(-`News reporting`)
```

```{r}
plot_fair_use <- function(data, category) {
  ggplot(data[data[[category]] == 1, ], aes(x = Outcome)) +
    geom_bar(fill = c("blue", "red")) +
    labs(title = paste("Fair Use Outcome for", category), x = "Outcome", y = "Frequency") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(size = 10, face = "plain"),
      axis.text = element_text(size = 10, face = "plain"),
      axis.title = element_text(size = 11, face = "plain"),
      plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
    )
}
```

```{r}
categories <- c("Education/Scholarship/Research", "Film/Audiovisual", "Music", "News Reporting", 
                "Painting/Drawing/Graphic", "Parody/Satire", "Photograph", "Review/Commentary", 
                "Computer Program", "Textual Work")

# Loop through each category and create the plot
for (category in categories) {
  print(plot_fair_use(fairuseindex, category))
}
```

#### Findings Over Year

```{r}
# Summarize the counts of fair use findings by year
yearly_counts <- fairuseindex %>% 
  group_by(Year, Outcome) %>% 
  summarize(Count = n()) %>% 
  ungroup()

# View the summarized data
head(yearly_counts)

# Plot of fair use findings over the years
ggplot(yearly_counts, aes(x = Year, y = Count, color = Outcome, group = Outcome)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  labs(title = "Fair Use Findings Over the Years", x = "Year", y = "Frequency") +
  scale_color_manual(values = c("Fair use found" = "blue", "Fair use not found" = "red")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10, face = "plain"),
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  )


# Filter the dataset to include only rows where the year is greater than or equal to 1976
fairuseindex_filtered <- fairuseindex %>% filter(Year >= 1976)


# Summarize the counts of fair use findings by year
yearly_counts_1 <- fairuseindex_filtered %>% 
  group_by(Year, Outcome) %>% 
  summarize(Count = n()) %>% 
  ungroup()

# View the summarized data
head(yearly_counts_1)

# Plot of fair use findings over the years
ggplot(yearly_counts_1, aes(x = Year, y = Count, color = Outcome, group = Outcome)) +
  geom_line(size = 1.5) +
  geom_point(size = 1) +
  geom_smooth(aes(group = Outcome, color = Outcome), method = "loess", se = FALSE, size = 1.5, linetype = "solid") +
  scale_color_manual(values = c("Fair use found" = "blue", "Fair use not found" = "red", 
                                "Trend Fair use found" = "darkblue", "Trend Fair use not found" = "darkred")) +
  labs(title = "Trend of Fair Use Findings Over the Years", x = "Year", y = "Frequency") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10, face = "plain"),
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  )

```

### Proportions

```{r}
library(dplyr)
library(ggplot2)

# Summarize the counts of fair use findings by medium
medium_counts <- fairuseindex %>%
  group_by(Medium, Outcome) %>%
  summarize(Count = n()) %>%
  ungroup()

# Calculate the total counts per medium
total_counts_per_medium <- medium_counts %>%
  group_by(Medium) %>%
  summarize(Total = sum(Count))

# Merge the total counts with the medium counts
medium_counts <- medium_counts %>%
  left_join(total_counts_per_medium, by = "Medium")

# Calculate the proportion
medium_counts <- medium_counts %>%
  mutate(Proportion = Count / Total)

head(medium_counts)

# Plot of medium by fair use outcome with proportions
ggplot(medium_counts, aes(x = Medium, y = Proportion, fill = Outcome)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = c("Fair use found" = "blue", "Fair use not found" = "red")) +
  labs(title = "Medium by Fair Use Outcome (Proportion)", x = "Medium", y = "Proportion", fill = "Outcome") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10, face = "plain"),
    axis.text = element_text(size = 10, face = "plain"),
    axis.title = element_text(size = 11, face = "plain"),
    plot.title = element_text(size = 13, face = "plain", hjust = 0.5)
  )

```

```{r}
# Contingency table of Medium vs Outcome
contingency_table <- table(fairuseindex$Medium, fairuseindex$Outcome)

print(contingency_table)

```

```{r}
#Chi-squared test
chi_squared_test <- chisq.test(contingency_table)

print(chi_squared_test)

```

```{r}
pairwise_chisq_test <- function(data, group_col, outcome_col) {
  # Get unique groups
  groups <- unique(data[[group_col]])
  
  # Initialize an empty list to store the results
  results <- list()
  
  # Perform pairwise Chi-squared tests
  for (i in 1:(length(groups) - 1)) {
    for (j in (i + 1):length(groups)) {
      group1 <- groups[i]
      group2 <- groups[j]
      
      # Filter data for the two groups
      data_subset <- data %>% filter(!!sym(group_col) %in% c(group1, group2))
      
      # Create a contingency table
      contingency_table <- table(data_subset[[group_col]], data_subset[[outcome_col]])
      
      # Perform the Chi-squared test
      chi_squared_test <- chisq.test(contingency_table)
      
      # Store the results
      results[[paste(group1, "vs", group2)]] <- chi_squared_test
    }
  }
  
  return(results)
}
```

```{r}
# Run the pairwise Chi-squared tests
pairwise_results <- pairwise_chisq_test(fairuseindex, "Medium", "Outcome")

# Extract p-values and apply Bonferroni correction
p_values <- sapply(pairwise_results, function(test) test$p.value)
adjusted_p_values <- p.adjust(p_values, method = "bonferroni")

adjusted_p_values
```
